/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentatie;

import logica.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.ButtonGroup;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Sebastiaan
 */
public class Beheervenster extends javax.swing.JFrame implements Filters{

    /**
     * Creates new form Beheervenster
     */
    Student student;
    Curriculum curriculum = new Curriculum();
    ArrayList<Vak> Fase1;
    ArrayList<Vak> Fase2;
    ArrayList<Vak> Fase3;
    private int somFase1 = 0;
    private int somFase2 = 0;
    private int somFase3 = 0;

    public Beheervenster() {
        initComponents();
        buttonEO.setVisible(false);
            ictWEB.setVisible(false);
            ictNET.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naamLabel = new javax.swing.JLabel();
        bewaarButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studiepuntenJaar1 = new javax.swing.JLabel();
        studiepuntenJaar2 = new javax.swing.JLabel();
        studiepuntenJaar3 = new javax.swing.JLabel();
        studiepuntenJaar4 = new javax.swing.JLabel();
        jaar1Naar2 = new javax.swing.JButton();
        jaar2Naar3 = new javax.swing.JButton();
        jaar3Naar4 = new javax.swing.JButton();
        jaar4Naar3 = new javax.swing.JButton();
        jaar2Naar1 = new javax.swing.JButton();
        jaar3Naar2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonEO = new javax.swing.JButton();
        ictWEB = new javax.swing.JButton();
        ictNET = new javax.swing.JButton();
        jErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        naamLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bewaarButton.setText("Bewaar programma");
        bewaarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bewaarButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane7.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane8.setViewportView(jTextArea4);

        jLabel1.setText("Jaar 1");

        jLabel2.setText("Jaar 2");

        jLabel3.setText("Jaar 3");

        jLabel4.setText("Jaar 4");

        studiepuntenJaar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        studiepuntenJaar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        studiepuntenJaar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        studiepuntenJaar4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jaar1Naar2.setText(">>>");
        jaar1Naar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaar1Naar2ActionPerformed(evt);
            }
        });

        jaar2Naar3.setText(">>>");
        jaar2Naar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaar2Naar3ActionPerformed(evt);
            }
        });

        jaar3Naar4.setText(">>>");
        jaar3Naar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaar3Naar4ActionPerformed(evt);
            }
        });

        jaar4Naar3.setText("<<<");
        jaar4Naar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaar4Naar3ActionPerformed(evt);
            }
        });

        jaar2Naar1.setText("<<<");
        jaar2Naar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaar2Naar1ActionPerformed(evt);
            }
        });

        jaar3Naar2.setText("<<<");
        jaar3Naar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaar3Naar2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Voornaam");

        jLabel6.setText("Achternaam");

        buttonEO.setText("Elektronica");
        buttonEO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEOActionPerformed(evt);
            }
        });

        ictWEB.setText("ictWEB");
        ictWEB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ictWEBActionPerformed(evt);
            }
        });

        ictNET.setText("ictNET");
        ictNET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ictNETActionPerformed(evt);
            }
        });

        jErrorLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(bewaarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(naamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studiepuntenJaar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jaar2Naar1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jaar1Naar2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studiepuntenJaar2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jaar2Naar3)
                                    .addComponent(jaar3Naar2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonEO)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ictWEB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ictNET))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(89, 89, 89)
                                            .addComponent(studiepuntenJaar3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jaar3Naar4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jaar4Naar3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studiepuntenJaar4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(buttonEO)
                                .addComponent(ictWEB)
                                .addComponent(ictNET)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bewaarButton)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7)
                                    .addComponent(jScrollPane6)
                                    .addComponent(jScrollPane5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jaar1Naar2)
                                .addGap(106, 106, 106)
                                .addComponent(jaar2Naar1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jaar2Naar3)
                        .addGap(114, 114, 114)
                        .addComponent(jaar3Naar2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jaar3Naar4)
                        .addGap(101, 101, 101)
                        .addComponent(jaar4Naar3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(studiepuntenJaar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(studiepuntenJaar2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studiepuntenJaar3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studiepuntenJaar4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bewaarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bewaarButtonActionPerformed
        curriculum = new Curriculum();

        try {
            
            student = new Student(jTextField1.getText(), jTextField2.getText(), curriculum);
            Fase1 = new ArrayList(filterFase(student.getCurriculum().getVakkenlijst(), "Fase1"));
            Collections.sort(Fase1);
            Fase2 = new ArrayList(filterFase(student.getCurriculum().getVakkenlijst(), "Fase2"));
            Collections.sort(Fase2);
            Fase3 = new ArrayList(filterFase(student.getCurriculum().getVakkenlijst(), "Fase3"));
            Collections.sort(Fase3);//all fine
            applyToFase();
            naamLabel.setText(jTextField1.getText() + " " + jTextField2.getText());
            studiepuntenJaar1.setText(somFase1 + "");
            studiepuntenJaar2.setText(somFase2 + "");
            studiepuntenJaar3.setText(somFase3 + "");
            buttonEO.setVisible(true);
            ictWEB.setVisible(true);
            ictNET.setVisible(true);
            
        } catch (Exception e) {
            jErrorLabel.setText(e+"");

        }
    }//GEN-LAST:event_bewaarButtonActionPerformed

    private void buttonEOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEOActionPerformed
        try {

            curriculum = new Curriculum();
            curriculum.setCurriculum(curriculum.toonVakkenElo(curriculum.getVakkenlijst()));             
            Collections.sort(curriculum.getVakkenlijst());
            student.setCurriculum(curriculum);
            applyToFase();

        } catch (Exception e) {
            jErrorLabel.setText(e+"");
        }

    }//GEN-LAST:event_buttonEOActionPerformed

    private void ictNETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ictNETActionPerformed
        try {

            curriculum = new Curriculum();
            curriculum.setCurriculum(curriculum.toonVakkenInfrastructuur(curriculum.getVakkenlijst()));             
            Collections.sort(curriculum.getVakkenlijst());
            student.setCurriculum(curriculum);
            applyToFase();


        } catch (Exception e) {
            jErrorLabel.setText(e+"");

        }
    }//GEN-LAST:event_ictNETActionPerformed

    private void ictWEBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ictWEBActionPerformed
        try {

            curriculum = new Curriculum();
            curriculum.setCurriculum(curriculum.toonVakkenInfrastructuur(curriculum.getVakkenlijst()));     //OOK WEER FASEN JUIST VULLEN        
            Collections.sort(curriculum.getVakkenlijst());
            student.setCurriculum(curriculum);
            applyToFase();

        } catch (Exception e) {
            jErrorLabel.setText(e+"");

        }
    }//GEN-LAST:event_ictWEBActionPerformed

    private void jaar1Naar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaar1Naar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaar1Naar2ActionPerformed

    private void jaar2Naar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaar2Naar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaar2Naar1ActionPerformed

    private void jaar2Naar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaar2Naar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaar2Naar3ActionPerformed

    private void jaar3Naar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaar3Naar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaar3Naar2ActionPerformed

    private void jaar3Naar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaar3Naar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaar3Naar4ActionPerformed

    private void jaar4Naar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaar4Naar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaar4Naar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beheervenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beheervenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beheervenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beheervenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beheervenster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bewaarButton;
    private javax.swing.JButton buttonEO;
    private javax.swing.JButton ictNET;
    private javax.swing.JButton ictWEB;
    private javax.swing.JLabel jErrorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jaar1Naar2;
    private javax.swing.JButton jaar2Naar1;
    private javax.swing.JButton jaar2Naar3;
    private javax.swing.JButton jaar3Naar2;
    private javax.swing.JButton jaar3Naar4;
    private javax.swing.JButton jaar4Naar3;
    private javax.swing.JLabel naamLabel;
    private javax.swing.JLabel studiepuntenJaar1;
    private javax.swing.JLabel studiepuntenJaar2;
    private javax.swing.JLabel studiepuntenJaar3;
    private javax.swing.JLabel studiepuntenJaar4;
    // End of variables declaration//GEN-END:variables

    private void applyToFase() {
        for (Vak v : Fase1) {
            jTextArea1.append(v.toString());
            somFase1 += v.getStdp();
        }
        for (Vak v : Fase2) {
            jTextArea2.append(v.toString());
            somFase2 += v.getStdp();
        }
        for (Vak v : Fase3) {
            jTextArea3.append(v.toString());
            somFase3 += v.getStdp();
        }

    }

    @Override
    public ArrayList<Vak> filterSemester(ArrayList<Vak> lijst, String semesters) {
       ArrayList<Vak> nieuw = new ArrayList();
        for (Vak vak : lijst) {
            if (vak.getSemester().equals(semesters)) {
                nieuw.add(vak);
               

            }

        }

        return nieuw;
    }

    @Override
    public ArrayList<Vak> filterFase(ArrayList<Vak> lijst, String fase) {
        ArrayList<Vak> nieuw = new ArrayList();
        for (Vak vak : lijst) {
            if (vak.getFase().equals(fase)) {
                nieuw.add(vak);
                //als fase gelijk is, toevoegen

            }

        }

        return nieuw;

    }

    @Override
    public void pasFaseToe() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
