/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentatie;

import logica.Kleur;
import java.awt.Color;
import java.awt.Graphics;
import logica.*;

/**
 *
 * @author Sebastiaan
 */
public class Cirkelpanel extends javax.swing.JPanel {

    /**
     * Creates new form Cirkelpanel
     */
    public Cirkelpanel() {
        initComponents();
    }
    private Color VIOLET = new Color(238, 130, 238);
    private Color INDIGO = new Color(75, 0, 130);

    private Kleur kleurcirkel;
    private Kleur kleurRand;
    private int randDikte;
    private double straal;
    Color inner;
    Color outer;
    Cirkel c;

    public void setCirkel(Cirkel c) {
        if (c != null) {
            this.c = c;
            this.straal = c.getStraal();
            this.kleurcirkel = c.getKleur();
            this.kleurRand = c.getKleurRand();
            this.randDikte = c.getDikteRand();
//        for (Kleur kleur : Kleur.values()) {
//             if (kleurcirkel == kleur) {
//                 inner = Color.getColor(kleurcirkel); ik wou dat er een normale manier was om dit op te lossen, maar na een half uur zoeken nog niks deftig gevonden./               
//            }
//      
//        }
//        for (Kleur kleur : Kleur.values()) {
//                   
//        }            

            if (kleurcirkel == Kleur.BLUE) {
                inner = Color.BLUE;

            }
            if (kleurcirkel == Kleur.ORANGE) {
                inner = Color.ORANGE;

            }
            if (kleurcirkel == Kleur.YELLOW) {
                inner = Color.YELLOW;

            }
            if (kleurcirkel == Kleur.RED) {
                inner = Color.RED;

            }
            if (kleurcirkel == Kleur.GREEN) {
                inner = Color.GREEN;

            }
            if (kleurcirkel == Kleur.INDIGO) {
                inner = INDIGO;

            }
            if (kleurcirkel == Kleur.VIOLET) {//tot hier voor kleur inner
                inner = VIOLET;

            }
            if (kleurRand == Kleur.BLUE) {
                inner = Color.BLUE;

            }
            if (kleurRand == Kleur.ORANGE) {
                inner = Color.ORANGE;

            }
            if (kleurRand == Kleur.YELLOW) {
                inner = Color.YELLOW;

            }
            if (kleurRand == Kleur.RED) {
                inner = Color.RED;

            }
            if (kleurRand == Kleur.GREEN) {
                inner = Color.GREEN;

            }
            if (kleurRand == Kleur.INDIGO) {
                inner = INDIGO;

            }
            if (kleurRand == Kleur.VIOLET) {
                inner = VIOLET;

            }

        }
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        int i = (int) straal;
        super.paintComponent(g);
        if (c != null) {
            g.setColor(outer);
            g.drawOval(c.getX(), c.getY(), i + randDikte, i + randDikte);//x1, y1, width, height
            g.fillOval(c.getX(), c.getY(), i + randDikte, i + randDikte);
            g.setColor(inner);
            g.drawOval(c.getX(), c.getY(), i, i);
            g.fillOval(c.getX(), c.getY(), i, i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
