/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentatie;
import logica.*;
import java.awt.Color;
import java.awt.Graphics;
import java.util.*;
import javax.swing.JPanel;

/**
 *
 * @author sebastiaan.debaedts
 */
public class Puntpanel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Puntpanel() {
        initComponents();
        
    }
    Punt p;
    public void setPunt(Punt p){
        if(p != null){
        this.p = p;            
        repaint();
        }
        
    }
    
    
    @Override
    protected void paintComponent(Graphics g){
               
        int breedte = this.getWidth();
        int hoogte = this.getHeight();
        super.paintComponent(g);
        g.setColor(Color.black);
        g.drawRect(10, 10, breedte -20, hoogte - 20);        
        g.setColor(Color.red);
        g.drawLine(breedte / 2, hoogte, breedte / 2, (hoogte * (-1)));
        g.drawLine(breedte *(-1), hoogte / 2, breedte, (hoogte /2));//x1, y1, x2, y2
        
        if(p != null){
            g.drawOval(breedte/2+p.getX(), hoogte / 2 - p.getY(), 1, 1);//x1, y1, width, height
            g.fillOval(breedte/2+p.getX(), hoogte / 2 - p.getY(), 1, 1);
        } 
        
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
