/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentatie;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import logica.Kleur;
import logica.*;

/**
 *
 * @author Sebastiaan
 */
public class Cirkelgui extends javax.swing.JFrame {

    private Figuur f;//f = new Vierkant();
    private Figuur f2;
    private Cirkel c;//moet niet meer gebruikt worden

    /**
     * Creates new form Cirkelgui
     */
    public Cirkelgui() {

        initComponents();
        this.kleurComboBox.setModel(new DefaultComboBoxModel(Kleur.values()));
        this.kleurRandComboBox.setModel(new DefaultComboBoxModel(Kleur.values()));

    }

    private int dikterand;
    private double straal;
    private Kleur kleur;
    private Kleur kleurRand;
    private boolean geplaatst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ErrorLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kleurComboBox = new javax.swing.JComboBox<>();
        kleurRandComboBox = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        straalTextField = new javax.swing.JTextField();
        knopCirkel = new javax.swing.JButton();
        cPanel = new Cirkelpanel();
        knopVierkant = new javax.swing.JButton();
        AfstandLabel = new javax.swing.JLabel();
        XcoordTextField = new javax.swing.JTextField();
        YcoordTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel2.setText("Kleur cirkel");

        jLabel3.setText("Kleur rand");

        jLabel4.setText("Dikte rand");

        jLabel5.setText("Straal/zijde");

        kleurComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        knopCirkel.setText("TEKEN Cirkel");
        knopCirkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopCirkelActionPerformed(evt);
            }
        });

        cPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout cPanelLayout = new javax.swing.GroupLayout(cPanel);
        cPanel.setLayout(cPanelLayout);
        cPanelLayout.setHorizontalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        cPanelLayout.setVerticalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        knopVierkant.setText("teken vierkant");
        knopVierkant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knopVierkantActionPerformed(evt);
            }
        });

        AfstandLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setLabelFor(XcoordTextField);
        jLabel1.setText("x");

        jLabel6.setLabelFor(YcoordTextField);
        jLabel6.setText("y");

        jLabel7.setText("AfstandVerschil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(430, 430, 430))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(knopCirkel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(knopVierkant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kleurComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kleurRandComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1)
                                    .addComponent(straalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(XcoordTextField)
                                .addComponent(AfstandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(YcoordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kleurComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kleurRandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XcoordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YcoordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AfstandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(straalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(knopCirkel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(knopVierkant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void knopCirkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopCirkelActionPerformed
        if (f != null) {
            try {
                kleur = (Kleur) kleurComboBox.getSelectedItem();
                kleurRand = (Kleur) kleurRandComboBox.getSelectedItem();
                this.f2 = new Cirkel(kleur, kleurRand, Integer.parseInt(jTextField1.getText()), new Punt(cPanel.getWidth() / 2, cPanel.getHeight() / 2), Integer.parseInt(straalTextField.getText()));
                ((Cirkelpanel) cPanel).repaint();

            } catch (IllegalArgumentException d) {
                ErrorLabel.setText(d + "");

            } catch (Exception e) {
                ErrorLabel.setText(e + "");

            }

        } else {
            try {
                kleur = (Kleur) kleurComboBox.getSelectedItem();
                kleurRand = (Kleur) kleurRandComboBox.getSelectedItem();
                this.f = new Cirkel(kleur, kleurRand, Integer.parseInt(jTextField1.getText()), new Punt(cPanel.getWidth() / 2, cPanel.getHeight() / 2), Integer.parseInt(straalTextField.getText()));
                ((Cirkelpanel) cPanel).repaint();
                geplaatst = true;

            } catch (IllegalArgumentException d) {
                ErrorLabel.setText(d + "");

            } catch (Exception e) {
                ErrorLabel.setText(e + "");

            }

        }

    }//GEN-LAST:event_knopCirkelActionPerformed

    private void knopVierkantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knopVierkantActionPerformed
        if (f != null) {
            try {
                kleur = (Kleur) kleurComboBox.getSelectedItem();
                kleurRand = (Kleur) kleurRandComboBox.getSelectedItem();
                this.f2 = new Vierkant(kleur, kleurRand, Integer.parseInt(jTextField1.getText()), new Punt(cPanel.getWidth() / 2, cPanel.getHeight() / 2), Integer.parseInt(straalTextField.getText()));
                ((Cirkelpanel) cPanel).repaint();

            } catch (IllegalArgumentException d) {//zijde ipv straal
                ErrorLabel.setText(d + "");

            } catch (Exception e) {
                ErrorLabel.setText(e + "");

            }
        } else {
            try {
                kleur = (Kleur) kleurComboBox.getSelectedItem();
                kleurRand = (Kleur) kleurRandComboBox.getSelectedItem();
                this.f = new Vierkant(kleur, kleurRand, Integer.parseInt(jTextField1.getText()), new Punt(cPanel.getWidth() / 2, cPanel.getHeight() / 2), Integer.parseInt(straalTextField.getText()));
                ((Cirkelpanel) cPanel).repaint();
                geplaatst = true;

            } catch (IllegalArgumentException d) {//zijde ipv straal
                ErrorLabel.setText(d + "");

            } catch (Exception e) {
                ErrorLabel.setText(e + "");

            }

        }

    }//GEN-LAST:event_knopVierkantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cirkelgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cirkelgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cirkelgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cirkelgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cirkelgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfstandLabel;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JTextField XcoordTextField;
    private javax.swing.JTextField YcoordTextField;
    private javax.swing.JPanel cPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> kleurComboBox;
    private javax.swing.JComboBox<String> kleurRandComboBox;
    private javax.swing.JButton knopCirkel;
    private javax.swing.JButton knopVierkant;
    private javax.swing.JTextField straalTextField;
    // End of variables declaration//GEN-END:variables
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
     */

    /**
     *
     * @author Sebastiaan
     */
    public class Cirkelpanel extends JPanel {

        /**
         * Creates new form Cirkelpanel
         */
        public Cirkelpanel() {
            initComponents();
        }
        private final Color VIOLET = new Color(238, 130, 238);
        private final Color INDIGO = new Color(75, 0, 130);

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (YcoordTextField.getText().trim().equals("") && XcoordTextField.getText().trim().equals("")) {//BIJ GEEN INPUT
                if (f != null && f instanceof Cirkel) {//CIRKEL
                    g.setColor(f.getKleurRand().vertaalKleur());
                    if (!geplaatst) {
                        g.fillOval(
                                f.getMiddelpunt().getX() - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                f.getMiddelpunt().getY() - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand()
                        );
                        g.setColor(f.getKleur().vertaalKleur());
                        g.fillOval(
                                f.getMiddelpunt().getX() + f.getDikteRand() / 2 - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                f.getMiddelpunt().getY() + f.getDikteRand() / 2 - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );
                    } else if (geplaatst && f2 instanceof Cirkel) {
                        g.setColor(f2.getKleurRand().vertaalKleur());
                        g.fillOval(
                                f2.getMiddelpunt().getX() - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                f2.getMiddelpunt().getY() - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()
                        );
                        g.setColor(f2.getKleur().vertaalKleur());
                        g.fillOval(
                                f2.getMiddelpunt().getX() + f2.getDikteRand() / 2 - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                f2.getMiddelpunt().getY() + f2.getDikteRand() / 2 - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );

                    }

                }
                if (f != null && f instanceof Vierkant) {//VIERKANT                
                    g.setColor(f.getKleurRand().vertaalKleur());
                    if (!geplaatst) {
                        g.fillRect(
                                (cPanel.getWidth() / 2) - (Integer.parseInt(straalTextField.getText()) + (f.getDikteRand())) / 2,
                                (cPanel.getHeight() / 2) - (Integer.parseInt(straalTextField.getText()) + (f.getDikteRand())) / 2,
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand()
                        );
                        g.setColor(f.getKleur().vertaalKleur());
                        g.fillRect(
                                (cPanel.getWidth() / 2) - (Integer.parseInt(straalTextField.getText())) / 2,
                                (cPanel.getHeight() / 2) - (Integer.parseInt(straalTextField.getText())) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );

                    } else if (geplaatst && f2 instanceof Vierkant) {
                        g.setColor(f2.getKleurRand().vertaalKleur());
                        g.fillRect(
                                (cPanel.getWidth() / 2) - (Integer.parseInt(straalTextField.getText()) + (f2.getDikteRand())) / 2,
                                (cPanel.getHeight() / 2) - (Integer.parseInt(straalTextField.getText()) + (f2.getDikteRand())) / 2,
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()
                        );
                        g.setColor(f2.getKleur().vertaalKleur());
                        g.fillRect(
                                (cPanel.getWidth() / 2) - (Integer.parseInt(straalTextField.getText())) / 2,
                                (cPanel.getHeight() / 2) - (Integer.parseInt(straalTextField.getText())) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );

                    }

                }

            } else if (!YcoordTextField.getText().trim().equals("") && !XcoordTextField.getText().trim().equals("")) //BIJ WEL INPUT
            {//als er wel coordinaten gegeven zijn
                if (f != null && f instanceof Cirkel) {
                    g.setColor(f.getKleurRand().vertaalKleur());//CIRKEL

                    if (!geplaatst) {
                        g.fillOval(
                                Integer.parseInt(XcoordTextField.getText()) - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                Integer.parseInt(YcoordTextField.getText()) - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand()
                        );
                        g.setColor(f.getKleur().vertaalKleur());
                        g.fillOval(
                                (Integer.parseInt(XcoordTextField.getText())) + f.getDikteRand() / 2 - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                (Integer.parseInt(XcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText()) + f.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );
                    } else if (geplaatst && f2 instanceof Cirkel){
                        g.fillOval(
                                Integer.parseInt(XcoordTextField.getText()) - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                Integer.parseInt(YcoordTextField.getText()) - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()
                        );
                        g.setColor(f2.getKleur().vertaalKleur());
                        g.fillOval(
                                (Integer.parseInt(XcoordTextField.getText())) + f2.getDikteRand() / 2 - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                (Integer.parseInt(XcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );

                    }

                }
                if (f != null && f instanceof Vierkant) {//VIERKANT                
                    g.setColor(f.getKleurRand().vertaalKleur());
                    if (!geplaatst) {
                        g.fillRect(
                                (Integer.parseInt(XcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText()) + (f.getDikteRand())) / 2,
                                (Integer.parseInt(YcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText()) + (f.getDikteRand())) / 2,
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f.getDikteRand()
                        );
                        g.setColor(f.getKleur().vertaalKleur());
                        g.fillRect(
                                (Integer.parseInt(XcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText())) / 2,
                                (Integer.parseInt(YcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText())) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );

                    } else if (geplaatst && f2 instanceof Vierkant) {
                        g.fillRect(
                                (Integer.parseInt(XcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText()) + (f2.getDikteRand())) / 2,
                                (Integer.parseInt(YcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText()) + (f2.getDikteRand())) / 2,
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand(),
                                Integer.parseInt(straalTextField.getText()) + f2.getDikteRand()
                        );
                        g.setColor(f2.getKleur().vertaalKleur());
                        g.fillRect(
                                (Integer.parseInt(XcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText())) / 2,
                                (Integer.parseInt(YcoordTextField.getText())) - (Integer.parseInt(straalTextField.getText())) / 2,
                                Integer.parseInt(straalTextField.getText()),
                                Integer.parseInt(straalTextField.getText())
                        );

                    }

                }
            }

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 400, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 300, Short.MAX_VALUE)
            );
        }// </editor-fold>                        

        // Variables declaration - do not modify                     
        // End of variables declaration                   
    }

}
